# Generated by Django 2.1.2 on 2021-04-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0014_auto_20210412_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Warden',
        ),
    ]
